const test=require('node:test');const assert=require('node:assert/strict');const {RadarProvider,selectFrames,framePath}=require('../lib/provider');const core=require('../public/core');
const latest=1700000100;const picture=(time,kind)=>({timestamp:time,data_type:kind,radar_url:'/product/output/radar/rzc/'+time+'.json'});
const animation={map_images:[{pictures:[picture(latest-300,'measurement'),picture(latest,'measurement'),picture(latest+300,'forecast'),picture(latest+36300,'forecast')]}]};
const raw={coords:{x_min:255.5,x_max:964.5,x_count:710,y_min:-159.5,y_max:479.5,y_count:640},areas:[]};
test('forecast includes the first available frame at or after the requested horizon',()=>{const s=selectFrames(animation,core.normalize({}));assert.equal(s.frames[s.frames.length-1].time,latest+36300);assert.equal(s.horizonLimited,false);});
test('observations-only configuration excludes forecasts',()=>{const s=selectFrames(animation,core.normalize({forecastHours:0}));assert.ok(s.frames.every(f=>f.kind==='measurement'));});
test('short horizon is explicit and manifest without observations is rejected',()=>{const s=selectFrames({map_images:[{pictures:animation.map_images[0].pictures.slice(0,3)}]},core.normalize({}));assert.ok(s.horizonLimited);assert.throws(()=>selectFrames({map_images:[{pictures:[]}]},core.normalize({})));});
test('arbitrary hosts and traversal cannot become frame fetches',()=>{for(const p of ['https://evil.example/file','/product/output/radar/../../secrets.json','/product/output/anything/x.json'])assert.throws(()=>framePath(p));});
test('network cache coalesces requests and bounds concurrency and memory',async()=>{let active=0,max=0,calls=0;const p=new RadarProvider({maxBytes:50,concurrency:2,fetch:async()=>{calls++;active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;return{value:'abcdefghij'};}});await Promise.all([p.json('same',1000),p.json('same',1000)]);assert.equal(calls,1);await Promise.all(['a','b','c','d'].map(k=>p.json(k,1000)));assert.ok(max<=2);assert.ok(p.bytes<=50);});
test('failed frames have null intensity, successful frames remain usable',async()=>{const p=new RadarProvider({fetch:async url=>{if(url.endsWith('versions.json'))return{'precipitation/animation':'v1'};if(url.endsWith('animation.json'))return animation;if(url.includes(String(latest+300)))throw Error('offline');return raw;}});const result=await p.series(core.normalize({}));assert.ok(result.partial);const failed=result.frames.find(f=>!f.available);assert.equal(failed.homeLevel,null);assert.equal(result.frames[0].homeLevel,0);});
test('all-frame failure rejects instead of reporting dry weather',async()=>{const p=new RadarProvider({fetch:async url=>{if(url.endsWith('versions.json'))return{'precipitation/animation':'v1'};if(url.endsWith('animation.json'))return animation;throw Error('offline');}});await assert.rejects(p.series(core.normalize({})),/unavailable/);});
test('matching concurrent instances account for shared prepared cache exactly once',async()=>{
  const p=new RadarProvider({fetch:async url=>url.endsWith('versions.json')?{'precipitation/animation':'v1'}:url.endsWith('animation.json')?animation:raw});
  await Promise.all([p.series(core.normalize({})),p.series(core.normalize({}))]);
  assert.equal(p.prepared.size,4);assert.equal(p.preparedBytes,[...p.prepared.values()].reduce((sum,v)=>sum+v.size,0));
});
