const test=require('node:test');const assert=require('node:assert/strict');const{parseHTML}=require('linkedom');const core=require('../public/core');
function setup(options){const{window,document}=parseHTML('<html><body><div id="root"></div></body></html>');global.window=window;global.document=document;window.matchMedia=()=>({matches:false});window.HTMLCanvasElement.prototype.getContext=function(){return{scale(){},clearRect(){},fill(){}};};global.Path2D=class{moveTo(){}lineTo(){}closePath(){}};const{View}=require('../public/view');return new View(document.getElementById('root'),core.normalize(Object.assign({autoplay:false},options)));}
const now=Math.floor(Date.now()/1000);const frames=[0,300,600].map((delta,i)=>({time:now+delta,kind:i?'forecast':'measurement',available:true,homeLevel:i,polygons:[]}));
const data={latestObservation:now,frames,partial:false,replay:false};
test('refresh preserves paused frame and configured playback speed',()=>{const v=setup({playbackSpeed:8});try{v.setData(data);v.slider.value=now+300;v.slider.oninput();v.setData(data);assert.equal(v.index,1);assert.equal(v.playing,false);assert.equal(v.speed,8);}finally{v.destroy();}});
test('scrubbing selects map and chart together; keyboard steps entire frames',()=>{const v=setup();try{v.setData(data);v.slider.value=now+590;v.slider.oninput();assert.equal(v.index,2);assert.equal(v.kind.textContent,'Forecast');assert.match(v.cursor.getAttribute('transform'),/translate/);v.slider.onkeydown({key:'Home',preventDefault(){},stopPropagation(){}});assert.equal(v.index,0);assert.equal(v.kind.textContent,'Observed');}finally{v.destroy();}});
test('missing frames are visibly unavailable, not drawn as dry',()=>{const v=setup();try{v.setData(Object.assign({},data,{partial:true,frames:[{time:now,kind:'measurement',available:false,homeLevel:null,polygons:[]}]}));assert.match(v.notice.textContent,/Frame unavailable/);assert.match(v.slider.getAttribute('aria-valuetext'),/Unavailable/);}finally{v.destroy();}});
const wet=Object.assign({},data,{frames:frames.map((f,i)=>Object.assign({},f,{polygons:i===1?[{color:'9ab7f5',rings:[]}]:[]}))});
test('suspend stops playback timers and resume retains desired playback',()=>{const v=setup({autoplay:true});try{v.setData(wet);assert.ok(v.timer);v.setSuspended(true);assert.equal(v.timer,null);assert.equal(v.playing,true);v.setSuspended(false);assert.ok(v.timer);}finally{v.destroy();assert.equal(v.destroyed,true);}});
test('marker labels are text, not injected HTML',()=>{const v=setup({markers:[{latitude:47.38,longitude:8.54,label:'<img src=x onerror=alert(1)>'}]});try{assert.equal(v.root.querySelectorAll('img').length,1);assert.ok(v.root.textContent.includes('<img src=x onerror=alert(1)>'));}finally{v.destroy();}});
test('forecast stays static during radar playback and refreshes independently',()=>{const v=setup({showWeather:true});try{const time=Math.ceil(Date.now()/3600000)*3600;const weather={fetchedAt:Date.now(),current:{time:Date.now()/1000,temp:12,feels:11,wind:2,code:800,night:true,description:'clear sky'},hourly:Array.from({length:14},(_,i)=>({time:time+i*3600,temp:12,wind:2,pop:.2,rain:0,code:800})),daily:[{time:time+86400,date:'2099-01-01',high:20,low:8,pop:.2,rain:0,code:800,wind:2}]};v.setWeather(weather);v.setData(data);const panel=v.weather.panels.firstChild;v.index=1;v.draw();assert.equal(v.weather.panels.firstChild,panel);assert.equal(v.root.querySelectorAll('.rr-weather-hour').length,4);v.setWeatherError('Offline');assert.equal(v.weather.notice.textContent,'Offline');assert.match(v.weather.now.textContent,/12°/);}finally{v.destroy();}});
test('a dry window holds the latest observation instead of animating',()=>{const v=setup({autoplay:true});try{v.setData(Object.assign({},data,{latestObservation:now+300}));assert.equal(v.timer,null);assert.equal(v.index,1);assert.equal(v.root.dataset.playing,'false');v.setData(wet);assert.ok(v.timer);assert.equal(v.root.dataset.playing,'true');}finally{v.destroy();}});
