const test=require('node:test'),assert=require('node:assert/strict');
const {WeatherProvider,normalize,condition,dayKey}=require('../lib/weather');const core=require('../public/core');const {blocks}=require('../public/weather-view');
const {readProbability,PARAMETERS}=require('../lib/weather-source');
const now=Date.parse('2026-09-25T20:15:00Z');const start=Math.ceil(now/3600000)*3600;
function raw(){const fields={};PARAMETERS.forEach(p=>fields[p]=new Map());for(let i=0;i<17;i++){const t=start+i*3600;fields.tre200h0.set(t,10+i);fields.fu3010h0.set(t,7.2);fields.rre150h0.set(t,i===2?1.5:0);fields.rp0003i0.set(t,30);fields.jww003i0.set(t,101);}for(let i=0;i<6;i++){const t=Date.parse('2026-09-25T00:00Z')/1000+i*86400;fields.tre200pn.set(t,8);fields.tre200px.set(t,20);fields.rka150p0.set(t,2);fields.jp2000d0.set(t,2);}return {fields,point:{id:'800100',type:'2',name:'Zurich'},issuedAt:now-900000,run:'one'};}
test('12-hour outlook covers four exact three-hour precipitation intervals',()=>{const data=normalize(raw(),now),h=blocks(data.hourly,now);assert.equal(h.length,4);assert.equal(h[0].time,start);assert.equal(h[3].end,start+12*3600);assert.equal(h[0].temp,13);assert.equal(h[0].rain,1.5);assert.equal(h[0].pop,.3);assert.equal(h[3].temp,22);assert.equal(data.current.wind,2);});
test('uses probability at interval end, not maximum of overlapping rolling probabilities',()=>{const r=raw();r.fields.rp0003i0.set(start+3600,90);r.fields.rp0003i0.set(start+10800,20);assert.equal(blocks(normalize(r,now).hourly,now)[0].pop,.2);});
test('missing values and hours are unavailable, not dry',()=>{const r=raw();r.fields.rre150h0.set(start+3600,null);r.fields.rp0003i0.delete(start+10800);const h=blocks(normalize(r,now).hourly,now);assert.equal(h[0].rain,null);assert.equal(h[0].pop,null);assert.throws(()=>normalize({fields:{}},now),/Incomplete/);});
test('Swiss daily totals remain calendar dates and have no invented daily probability',()=>{const d=normalize(raw(),now);assert.equal(d.daily[1].date,'2026-09-26');assert.equal(d.daily[1].pop,null);assert.equal(d.daily[1].rain,2);assert.equal(dayKey(Date.parse('2026-10-25T23:30Z')/1000,'Europe/Zurich'),'2026-10-26');});
test('MeteoSwiss day/night, rain/snow and thunderstorm symbols map to original drawings',()=>{assert.equal(condition(101).night,true);assert.equal(condition(101).code,800);assert.equal(condition(20).code,500);assert.equal(condition(121).code,611);assert.equal(condition(22).code,600);assert.equal(condition(138).code,200);assert.equal(condition(null).code,null);assert.equal(condition(999).code,null);});
test('range lookup extracts a complete point with a bounded transfer',async()=>{
 let csv='point_id;point_type_id;Date;rp0003i0\n';for(let id=1;id<=200;id++)for(let hour=0;hour<216;hour++){const date=new Date(start*1000+hour*3600000).toISOString().replace(/[-:T]/g,'').slice(0,12);csv+=id+';2;'+date+';'+(id===100?30:90)+'\n';}
 let bytes=0;const request=async(url,start,end)=>{assert.ok(end-start<40000);const text=csv.slice(start,end+1);bytes+=text.length;return {start,total:csv.length,text,bytes:text.length};};
 const result=await readProbability('test',{id:'100',type:'2'},request);assert.equal(result.values.size,216);assert.ok([...result.values.values()].every(v=>v===30));assert.ok(bytes<150000);assert.ok(bytes<csv.length/4);
});
test('range lookup rejects a changed CSV header instead of inventing probabilities',async()=>{await assert.rejects(readProbability('test',{id:'100',type:'2'},async()=>({start:0,total:30,text:'invalid columns\n',bytes:16})),/schema/);});
test('deduplicates calls and reuses extracted data until a new source run is published',async()=>{let calls=0,clock=now,r=raw(),fail=false;const source={latest:async()=>({issuedAt:r.issuedAt,run:r.run}),load:async()=>{calls++;if(fail)throw Error('offline');return r;}};const p=new WeatherProvider({source,now:()=>clock}),config=core.normalize({});const [a,b]=await Promise.all([p.forecast(config),p.forecast(config)]);assert.equal(a,b);assert.equal(calls,1);clock+=900001;await p.forecast(config);assert.equal(calls,1);clock+=900001;r=raw();r.issuedAt+=3600000;r.run="two";fail=true;await assert.rejects(p.forecast(config));fail=false;await p.forecast(config);assert.equal(calls,3);});
